### ISSUE TITLE
Horse issues

### ISSUE THREAD

**Issue by Ibotmealot** [YouHaveTrouble/PreventStabby#11]
A player on my server seems to be unable to eat golden carrots near horses, unless they turn pvp on. They're playing on bedrock (with Nintendo switch), however, floodgate is installed on the server. T

https://youtu.be/HCcJqhSpXwQ and https://youtu.be/d-fMoVcVKzI

**Comment by YouHaveTrouble** [comment]
That looks like a very funny bug. Thankfully it's not on my side if it doesn't happen to regular players on java client. I have no say or tell how protocol hack handles its inner workings, nor am I willing to spend time to find a workaround for it. Feel free to report this to creators fo floodgate.

**Comment by Camotoy** [comment]
For future reference, gameplay mechanics are all on the Geyser end. Floodgate only handles some API and authentication. We'll handle the issue reporting process from here though.

**Comment by YouHaveTrouble** [comment]
> For future reference, gameplay mechanics are all on the Geyser end. Floodgate only handles some API and authentication. We'll handle the issue reporting process from here though.

Good to know. Thanks for clarifying. :)
