### ISSUE TITLE
Cannot Kill Pets When PvP Force Enabled

### ISSUE THREAD

**Issue by GitNuck** [YouHaveTrouble/PreventStabby#15]
When I force enable PvP pets are impossible to kill and remain invulnerable.  Latest version on the latest Purpur, (1976).

**Comment by YouHaveTrouble** [comment]
I have a potential fix for this, if you could test it out, please join the [discord server](https://discord.gg/j8KK5dGBps) and after we confirm it works I'll make a public release

**Comment by YouHaveTrouble** [comment]
Fixed in release 1.10.2

**Comment by GitNuck** [comment]
Thank-you for the quick response and fix!
