### ISSUE TITLE
Failing to load plugin

### ISSUE THREAD

**Issue by Uboaaaaa** [YouHaveTrouble/PreventStabby#5]
Console error log: https://paste.gg/p/anonymous/a18b7d4c2c454ca5ad64c1c4d83c3340

Game version: 1.16.5
Server core: Yatopia

**Comment by YouHaveTrouble** [comment]
> Server core: Yatopia

there's your issue. Try [Tuinity](https://ci.codemc.io/job/Spottedleaf/job/Tuinity/) or [Purpur](https://purpur.pl3x.net/downloads/#1.16.5)

Yatopia breaks shit it shouldn't even touch.
