### ISSUE TITLE
suggestion: global toggles

### ISSUE THREAD

**Issue by emielderckx** [YouHaveTrouble/PreventStabby#6]
1. `/pvpall true/false` change the pvp status of everyone
2.  `/pvpblock true/false` change if players can toggle there pvp status

these things are handy at server openings and events etc

**Comment by Romvnly-Gaming** [comment]
why not just make it a worldguard region and disable pvp like dat

**Comment by YouHaveTrouble** [comment]
Idea implemented in  [v1.6.0](https://github.com/YouHaveTrouble/PreventStabby/releases/tag/v1.6.0).
I opted not to modify actual saved pvp states of players, the command added just overwrites the result of canDamage function until server restart. In other cases you can use config option to set default pvp state.
